### ISSUE TITLE
send correct wallet type and subtype to the backend

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1049]
on PUT and POST to /users/me:
send the following properties of the user "object"
```
      wallet_type:
        example: browser
        type: string
        enum: [ledger, browser, light, unknown]
      wallet_subtype:
        example: metamask
        type: string
        enum: [metamask, parity, unknown]
```
