### ISSUE TITLE
[Post investment] Investor epic

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4452]
**Background**
 Post investment has to do with the governance needs of a company, required legally as well as due to the agreement an issuer has with shareholders.

For more information and background details read here: https://neufund.atlassian.net/l/c/QXrYwfXZ

This Epic deals with the changes to the investor dashboard we required to allow investors to see more information on assets they hold in their portfolio, especially the shared general information received from the issuers (as developed in this Issuer Post Investment epic that’s in development: https://github.com/Neufund/platform-frontend/issues/4358) .

**Designs** 
See the designs here in Zeplin under _Post Investment > Investor views: _ https://app.zeplin.io/project/5e5fb4508e2ebb14273bf54d/dashboard?seid=5ee73c4751555bb33c530506

The components are also in the style guide and are grouped on this view here: https://app.zeplin.io/project/5e5fb4508e2ebb14273bf54d/screen/5ee73e7914cfd8b664a2099b/

These screens represent the user flow. There is also a Figma prototype available, please ask @andywalton for the link.

**An overview of the portfolio item detail view:**

* As an investor, I can navigate to a new Portfolio detail view when I click on any assets I own. For instance, each will have a unique detail url, something like: `platform.neufund.org/portfolio/<token_name>/`

* On this Portfolio asset detail view, there it is basically split into a 2/3 content section with a 1/3 side column useful action tools. This side column is sticky and follows along as the user as they scroll down the page.

* The aim of these detail pages is to show an investor information on the asset they hold, such as: the current value in EUR, how many tokens they have (number of tokens), what % of total tokens do they own, what does this equate to in terms of a shareholding, what’s the market cap, current company valuation, how many other token holder investor are there? What is the cap table breakdown. Summary information about the company, useful links (web, social media etc.), the transactions they made in order to gain the current position with the asset, and lastly, any “Governance / Post Investment” shareholder updates, dividends, things they should vote on or officially know from the company and any documents the investor might want to download in regards to this investment.

* The “Back to Portfolio” link above the page title links back to the Portfolio view

* This detail view will only be shown for assets you hold. Portfolio assets that are still campaigning, will continue to redirect a user to their campaign page.

* The Send FFT (token) widget should simply kick off our send token wizard. The amount entered in the amount input field should simply pull through if it exists.

**Take note:** 
> For now, NEU won’t have a detail page as it needs to be handled differently that ETO tokens. This NEU page will need to include a payouts section and potentially a graph showing how NEU has been distributed to date and is still available. The actions might also need to be more broad. Therefore, don’t link NEU yet to a detail page.

**Technical notes**
@Rudolfix please add.

**Testing notes** 
@Nikola, I’ll invite you to the developer handover for Frontend as we discuss this work so that you know what to test and can plan for it.

Please speak to @andywalton @rudolfix @pstroinski with any questions.

**Comment by Moejoe90** [comment]
Questions for sync meeting: 

- I couldn't fully understand `users that never had any tokens of the issuer. all other cases (class C)`
a - Does this mean these users cannot see the token but can still access the general info page 
b - Does this mean that link is public

**Comment by andywalton** [comment]
@Moejoe90 @arjunu 

As discussed last week, we're should focus initially on building the investor portfolio detail view for Class A - current token holders. We can do Class B & C with later phases.

Secondly, the notification banner on the Dashboard, this should remain and not go away initially. Once we have the portfolio detail banner in place. Please make this banner dismissable.

**Comment by rudolfix** [comment]
backend is implemented:

**About**
take cap table, company and nominee data from new `eto listing` endpoint.
```
/companies_view/{id}:
    get:
      operationId: api.company_view.get
      tags:
      - Company View
      parameters:
      - name: id
        in: path
        type: string
        required: true
        pattern: ^0x[a-fA-F0-9]{40}$
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/CompanyView"
        404:
          description: Company not found
```
please take everything else from the smart contracts directly as specified in ticket above

**list of resolution with titles and download buttons**
please follow the same procedure as in https://github.com/Neufund/platform-frontend/issues/4358#issuecomment-668004347.
`company_view` contains the same `documents` collection as company data.

**download buttons - checking permissions to document**
you must disable download buttons when `uid` has no permission to download. there's new `immutable storage` endpoint. you must pass JWT to it:
```
/documents/{ipfs_hash_list}/envelopes:
    get:
      operationId: api.document.envelopes
      summary: 'Returns envelopes for a list of ipfs hashes, optionally resolving ACLs'
      parameters:
        - in: path
          name: ipfs_hash_list
          required: true
          description: A comma-separated list of ipfs hashes (without ipfs:prefix}
          type: array
          items:
            type: string
            pattern: ^Qm[a-zA-Z1-9]+$
          collectionFormat: csv
          minItems: 1
        - in: query
          name: access_check
          required: false
          description: optionally check access to document for authorized uid
          type: boolean
          default: false
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/EnvelopesResponse"
```
it returns dictionary http status: envelope
```
EnvelopesResponse:
    type: object
    additionalProperties:
      $ref: "#/definitions/EnvelopeWithAccess"

  EnvelopeWithAccess:
    type: object
    additionalProperties: false
    required: [status]
    properties:
      status:
        description: HTTP like status 200, 404, 401 (access denied), 403 (envelope tampered)
        type: integer
      envelope:
        description: document envelope if found and not legacy document
        $ref: "#/definitions/ImmutableDocumentEnv"
```

**filtered transaction list**
use the same endpoint that is used to get transaction, but pass additional query parameter:
```
/transactions/me:
    get:
      operationId: api.transactions.get_transactions_me
      tags:
        - Transactions
      parameters:
        - name: before_transaction
          in: query
          type: string
          description: Only return results earlier than this transaction
        - name: limit
          in: query
          type: integer
        - name: use_fixtures
          in: query
          type: boolean
        - in: query
          name: filtered_contracts
          type: array
          items:
            type: string
            # won't allow #/definitions/ChecksumAddress here
            pattern: ^0x[a-fA-F0-9]{40}$
          collectionFormat: csv
          minItems: 1
          description: A list of smart contracts address to filter for, typicaly token or commitment addresses
          required: false
```
pass equity token address, all eto addresses and token controller address to `filtered_contracts`
